// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0054:Use compound assignment", Justification = "Library", Scope = "member", Target = "~M:WindowsInput.Simulate.Events(WindowsInput.Events.InvokeOptions,System.Collections.Generic.IEnumerable{WindowsInput.Events.IEvent})~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:WindowsInput.Events.Sources.AsyncKeyboardEventSource.AsyncObject")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:WindowsInput.Events.Sources.AsyncMouseEventSource.AsyncObject")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Native.ButtonCodeExtensions.ToMouseWheel(WindowsInput.Events.ButtonCode)~WindowsInput.Native.MouseFlag")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Native.ButtonCodeExtensions.ToMouseWheel(WindowsInput.Events.ButtonCode)~WindowsInput.Native.MouseFlag")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Events.Sources.HookEventSource.InvokeEvent``1(WindowsInput.Events.Sources.EventSourceEventArgs,System.EventHandler{WindowsInput.Events.Sources.EventSourceEventArgs{``0}},``0,System.Object,System.DateTimeOffset)~WindowsInput.Events.Sources.EventSourceEventArgs")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Events.Sources.KeyboardEvent.#ctor(WindowsInput.Events.Wait,WindowsInput.Events.KeyDown,WindowsInput.Events.TextClick,WindowsInput.Events.KeyUp)")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Events.Sources.KeyboardEventSourceState.ClearKeyboardBuffer(WindowsInput.Events.KeyCode,System.Int32,WindowsInput.Native.KeyboardLayout)")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Native.ButtonCodeExtensions.ToMouseButtonDownFlags(WindowsInput.Events.ButtonCode)~WindowsInput.Native.MouseFlag")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Native.ButtonCodeExtensions.ToMouseButtonDownFlags(WindowsInput.Events.ButtonCode)~WindowsInput.Native.MouseFlag")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Native.ButtonCodeExtensions.ToMouseButtonUpFlags(WindowsInput.Events.ButtonCode)~WindowsInput.Native.MouseFlag")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Native.ButtonCodeExtensions.ToMouseButtonUpFlags(WindowsInput.Events.ButtonCode)~WindowsInput.Native.MouseFlag")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Native.KeyboardLayout.Current~WindowsInput.Native.KeyboardLayout")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Native.KeyboardLayout.ToChar(WindowsInput.Events.KeyCode,System.Boolean@)~System.Nullable{System.Char}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Events.Sources.MouseEvent.#ctor(WindowsInput.Events.Wait,WindowsInput.Events.MouseMove,WindowsInput.Events.ButtonScroll,WindowsInput.Events.ButtonDown,WindowsInput.Events.ButtonUp,WindowsInput.Events.ButtonClick,WindowsInput.Events.ButtonClickHold,WindowsInput.Events.ButtonDoubleClick,System.Collections.Generic.IReadOnlyCollection{WindowsInput.Events.DragStart},System.Collections.Generic.IReadOnlyCollection{WindowsInput.Events.DragDrop})")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Native.KeyboardState.Current~WindowsInput.Native.KeyboardState")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression", Justification = "<Pending>", Scope = "member", Target = "~M:WindowsInput.Native.MouseMovementExtensions.ToMouseFlags(WindowsInput.Events.MouseOffset)~WindowsInput.Native.MouseFlag")]
